"""update table manager quota

Revision ID: 18ad93e07535
Revises: 6c73b195a0ce
Create Date: 2025-08-22 15:30:40.919578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ad93e07535'
down_revision: Union[str, None] = '6c73b195a0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.drop_table('managerquota')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_quota',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('manager_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
        sa.Column('quota', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('period_start', sa.Date(), nullable=False),
        sa.Column('period_end', sa.Date(), nullable=False),
        sa.Column('remuneration', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    
    op.create_index('ix_manager_quota_manager_id', 'manager_quota', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('managerquota')
