"""a migration unique enc

Revision ID: 3c1a626261d9
Revises: ba4868398778
Create Date: 2025-06-29 01:21:57.784033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1a626261d9'
down_revision: Union[str, None] = 'ba4868398778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wash_record_user_id', table_name='wash_record')
    op.drop_table('wash_record')
    # Ajouter la table WashRecord
    op.create_table('wash_record',
        sa.Column('id', sa.INTEGER(), autoincrement=True, primary_key=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
        sa.Column('wash_date', sa.DATE(), nullable=False),
        sa.Column('wash_id', sa.Integer(), nullable=False, unique=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wash_record_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='wash_record_pkey'),
        sa.UniqueConstraint('wash_id', name='wash_record_wash_id_key')
    )
    op.create_index('ix_wash_record_user_id', 'wash_record', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wash_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wash_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('wash_id', sa.Integer(), nullable=False, unique=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wash_record_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wash_record_pkey'),
    sa.UniqueConstraint('wash_id', name='wash_record_wash_id_key')
    )
    op.create_index('ix_wash_record_user_id', 'wash_record', ['user_id'], unique=False)
    # ### end Alembic commands ###
