"""update tables

Revision ID: 45b11db8c1b9
Revises: 9594ad4f9b7c
Create Date: 2025-08-19 11:44:42.701226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b11db8c1b9'
down_revision: Union[str, None] = '9594ad4f9b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wash_record_user_id', table_name='wash_record')
    op.drop_table('wash_record')
    op.add_column('benefit', sa.Column('permission_name', sa.String(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('benefit', 'permission_name')
    op.create_table('wash_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wash_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('wash_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wash_record_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wash_record_pkey'),
    sa.UniqueConstraint('wash_id', name='wash_record_wash_id_key')
    )
    op.create_index('ix_wash_record_user_id', 'wash_record', ['user_id'], unique=False)
    # ### end Alembic commands ###
