"""Ajout de record a la  migration

Revision ID: 49dd328caca0
Revises: c98311e6f265
Create Date: 2025-06-28 23:29:09.176022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dd328caca0'
down_revision: Union[str, None] = 'c98311e6f265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managerquota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('remuneration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

     # Ajouter la table WashRecord
    op.create_table(
        'wash_record',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id', ondelete='CASCADE'), nullable=False),
        sa.Column('wash_date', sa.Date(), nullable=False),
        sa.Column('wash_id', sa.String(length=255), nullable=False, unique=True),
    )
    op.create_index(op.f('ix_wash_record_user_id'), 'wash_record', ['user_id'], unique=False)
    
    op.drop_index('ix_manager_quota_user_id', table_name='manager_quota')
    op.drop_table('manager_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_quota',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quota', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('remuneration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='manager_quota_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='manager_quota_pkey')
    )
    op.create_index('ix_manager_quota_user_id', 'manager_quota', ['user_id'], unique=False)
    op.drop_table('managerquota')
    
    # Supprimer la table WashRecord
    op.drop_index(op.f('ix_wash_record_user_id'), table_name='wash_record')
    op.drop_table('wash_record')
    # ### end Alembic commands ###
