"""garage_for_wash

Revision ID: 69ad893d8e1e
Revises: 18ad93e07535
Create Date: 2025-09-02 22:53:50.870479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69ad893d8e1e'
down_revision: Union[str, None] = '18ad93e07535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_wash',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_wash_employee',
        sa.Column('car_wash_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['car_wash_id'], ['car_wash.id'], ),
        sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('car_wash_id', 'employee_id')
    )
    op.create_table('stock_managments',
        sa.Column('station_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['station_id'], ['car_wash.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.drop_table('garage')
    op.drop_index('ix_manager_quota_manager_id', table_name='manager_quota')
    op.alter_column('wash_record', 'wash_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_wash_record_manager_id', table_name='wash_record')
    op.drop_constraint('fk_wash_record_wash_id_user', 'wash_record', type_='foreignkey')
    op.drop_constraint('wash_record_wash_id_fkey', 'wash_record', type_='foreignkey')
    op.create_foreign_key(None, 'wash_record', 'user', ['wash_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wash_record', type_='foreignkey')
    op.create_foreign_key('wash_record_wash_id_fkey', 'wash_record', 'user', ['wash_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_wash_record_wash_id_user', 'wash_record', 'user', ['wash_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_wash_record_manager_id', 'wash_record', ['manager_id'], unique=False)
    op.alter_column('wash_record', 'wash_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_manager_quota_manager_id', 'manager_quota', ['manager_id'], unique=False)
    op.create_table('garage',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='garage_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='garage_pkey')
    )
    op.drop_table('stock_managments')
    op.drop_table('car_wash_employee')
    op.drop_table('car_wash')
    # ### end Alembic commands ###
