"""sotck_history

Revision ID: 871e4043906f
Revises: 0e3b3e5c160e
Create Date: 2025-09-03 12:10:31.784743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871e4043906f'
down_revision: Union[str, None] = '0e3b3e5c160e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_car_wash_user_id', table_name='car_wash')
    op.create_table('stock_histories',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('operation', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('last_updated', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['stock_id'], ['stock_managments.id'], name='stock_managments_history_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='stock_histories_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_car_wash_user_id', 'car_wash', ['user_id'], unique=False)
    # ### end Alembic commands ###
