"""Fix garage foreign key and update schema

Revision ID: ad9739634cf2
Revises: f82dc0afdaa7
Create Date: 2025-04-19 18:13:56.974848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9739634cf2'
down_revision: Union[str, None] = 'f82dc0afdaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offerbenefit',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'benefit_id')
    )
    op.drop_table('offer_benefit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_benefit',
    sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('benefit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], name='offer_benefit_benefit_id_fkey'),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], name='offer_benefit_offer_id_fkey'),
    sa.PrimaryKeyConstraint('offer_id', 'benefit_id', name='offer_benefit_pkey')
    )
    op.drop_table('offerbenefit')
    # ### end Alembic commands ###
