"""update benefit create

Revision ID: af8a195d3d48
Revises: fbab7c0bedca
Create Date: 2025-04-20 17:52:29.151352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af8a195d3d48'
down_revision: Union[str, None] = 'fbab7c0bedca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefit', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('benefit', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('benefit', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('benefit', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('benefit', 'image')
    op.drop_column('benefit', 'description')
    # ### end Alembic commands ###
