"""Ajout de record a la  migration unique enc

Revision ID: ba4868398778
Revises: 0095bfbbc8c4
Create Date: 2025-06-29 01:14:22.952428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4868398778'
down_revision: Union[str, None] = '0095bfbbc8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wash_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wash_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('wash_id', sa.Integer(), nullable=False, unique=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wash_record_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wash_record_pkey'),
    sa.UniqueConstraint('wash_id', name='wash_record_wash_id_key')
    )
    op.create_index('ix_wash_record_user_id', 'wash_record', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wash_record')
    # ### end Alembic commands ###
