"""Add relationship user with garage

Revision ID: defc8c924559
Revises: af8a195d3d48
Create Date: 2025-05-29 12:27:51.825388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defc8c924559'
down_revision: Union[str, None] = 'af8a195d3d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_garage_id', 'user', type_='foreignkey')
    op.drop_column('user', 'garage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('garage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_user_garage_id', 'user', 'garage', ['garage_id'], ['id'])
    # ### end Alembic commands ###
